// <auto-generated />
namespace EntityFrameworkExample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class StoreMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StoreMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202004131317162_StoreMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
